// ══════════════════════════════════════════════════════
//  DATA: ALBUMS
// ══════════════════════════════════════════════════════
const ALBUMS = [

// ─── KANYE WEST ───────────────────────────────────────
{
  id: "the-college-dropout",
  title: "The College Dropout",
  artist: "Kanye West",
  year: "2004",
  type: "official",
  tags: ["kanye","west","college","dropout","rap","hip hop","2004"],
  cover: "https://i.scdn.co/image/ab67616d0000b27325b055377757b3cdd6f26b78",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kanye-west/the-college-dropout/",
  tracks: [
    {name:"Intro (Skit)",file:"intro.mp3",statId:"#CD_INTRO"},
    {name:"We Don't Care",file:"we-dont-care.mp3",statId:"#CD_WDC"},
    {name:"Graduation Day",file:"graduation-day.mp3",statId:"#CD_GRAD"},
    {name:"All Falls Down",file:"all-falls-down.mp3",statId:"#CD_AFD"},
    {name:"I'll Fly Away",file:"fly-away.mp3",statId:"#CD_IFA"},
    {name:"Spaceship",file:"spaceship.mp3",statId:"#CD_SPACE"},
    {name:"Jesus Walks",file:"jesuswalks.mp3",statId:"#CD_JW"},
    {name:"Never Let Me Down",file:"never-let-me-down.mp3",statId:"#CD_NLMD"},
    {name:"Get Em High",file:"get-em-high.mp3",statId:"#CD_GEH"},
    {name:"Workout Plan (Skit)",file:"workout-plan.mp3",statId:"#CD_WPS"},
    {name:"The New Workout Plan",file:"new-workout-plan.mp3",statId:"#CD_TNWP"},
    {name:"Slow Jamz",file:"slow-jamz.mp3",statId:"#CD_SJ"},
    {name:"Breathe In Breathe Out",file:"bibo.mp3",statId:"#CD_BIBO"},
    {name:"School Spirit (Skit 1)",file:"school-spirit-skit-1.mp3",statId:"#CD_SSS1"},
    {name:"School Spirit",file:"school-spirit.mp3",statId:"#CD_SS"},
    {name:"School Spirit (Skit 2)",file:"school-spirit-skit-2.mp3",statId:"#CD_SSS2"},
    {name:"Lil Jimmy (Skit)",file:"lil-jimmy-skit.mp3"},
    {name:"Two Words",file:"2words.mp3",statId:"#CD_2W"},
    {name:"Through the Wire",file:"through-the-wire.mp3",statId:"#CD_TTW"},
    {name:"Family Business",file:"family-business.mp3",statId:"#CD_FB"},
    {name:"Last Call",file:"lastcall.mp3",statId:"#CD_LC"}
  ]
},
{
  id: "late-registration",
  title: "Late Registration",
  artist: "Kanye West",
  year: "2005",
  type: "official",
  tags: ["kanye","west","late","registration","gold digger","diamonds","rap","hip hop","2005"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/Late_registration_cd_cover.jpg/250px-Late_registration_cd_cover.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kanye-west/late-registration/",
  tracks: [
    {name:"Wake Up Mr. West (Skit)",file:"wake-up-mr_west.mp3"},
    {name:"Heard 'Em Say",file:"heard-em-say.mp3",statId:"#LR_HES"},
    {name:"Touch the Sky",file:"touch-the-sky.mp3",statId:"#LR_TTS"},
    {name:"Gold Digger",file:"gold-digger.mp3",statId:"#LR_GD"},
    {name:"Drive Slow",file:"drive-slow.mp3",statId:"#LR_DS"},
    {name:"My Way Home (Skit)",file:"my-way-home-skit.mp3"},
    {name:"Crack Music",file:"crack-music.mp3",statId:"#LR_CM"},
    {name:"Roses",file:"roses.mp3",statId:"#LR_ROSES"},
    {name:"Bring Me Down",file:"bring-me-down.mp3",statId:"#LR_BMD"},
    {name:"Addiction",file:"addiction.mp3",statId:"#LR_ADD"},
    {name:"Diamonds from Sierra Leone (Remix)",file:"diamonds.mp3",statId:"#LR_DIAM"},
    {name:"We Major",file:"we-major.mp3",statId:"#LR_WM"},
    {name:"Hey Mama",file:"hey-mama.mp3",statId:"#LR_HM"},
    {name:"Celebration",file:"celebration.mp3",statId:"#LR_CEL"},
    {name:"Gone",file:"gone.mp3",statId:"#LR_GONE"},
    {name:"Late",file:"late.mp3",statId:"#LR_LATE"},
    {name:"Number One",file:"number-one.mp3",statId:"#LR_N1"},
    {name:"We Can Make It Better",file:"we-can-make-it.mp3",statId:"#LR_WCMIB"}
  ]
},
{
  id: "graduation",
  title: "Graduation",
  artist: "Kanye West",
  year: "2007",
  type: "official",
  tags: ["kanye","west","graduation","stronger","good morning","rap","hip hop","2007"],
  cover: "https://m.media-amazon.com/images/I/71pxGj4RoVS._AC_UF894,1000_QL80_.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kanye-west/graduation/",
  tracks: [
    {name:"Good Morning",file:"good-morning.mp3",statId:"#GR_GM"},
    {name:"Champion",file:"champion.mp3",statId:"#GR_CHAMP"},
    {name:"Stronger",file:"stronger.mp3",statId:"#GR_STR"},
    {name:"I Wonder",file:"i-wonder.mp3",statId:"#GR_IW"},
    {name:"Good Life",file:"good-life.mp3",statId:"#GR_GL"},
    {name:"Can't Tell Me Nothing",file:"cant-tell-me-nothing.mp3",statId:"#GR_CTMN"},
    {name:"Barry Bonds",file:"barry-bonds.mp3",statId:"#GR_BB"},
    {name:"Drunk and Hot Girls",file:"drunk-hot-girls.mp3",statId:"#GR_DHG"},
    {name:"Flashing Lights",file:"flashing-lights.mp3",statId:"#GR_FL"},
    {name:"Everything I Am",file:"everything-i-am.mp3",statId:"#GR_EIA"},
    {name:"The Glory",file:"the-glory.mp3",statId:"#GR_TG"},
    {name:"Homecoming",file:"homecoming.mp3",statId:"#GR_HC"},
    {name:"Big Brother",file:"big-brother.mp3",statId:"#GR_BIG"}
  ]
},
{
  id: "808s",
  title: "808s & Heartbreak",
  artist: "Kanye West",
  year: "2008",
  type: "official",
  tags: ["kanye","west","808s","heartbreak","heartless","love lockdown","autotune","rap","pop","2008"],
  cover: "https://m.media-amazon.com/images/I/51-HCBAsFRL._UF1000,1000_QL80_.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kanye-west/808s-n-heartbreak/",
  tracks: [
    {name:"Say You Will",file:"say-you-will.mp3",statId:"#808_SYW"},
    {name:"Welcome to Heartbreak",file:"welcome-to-heartbreak.mp3",statId:"#808_WTH"},
    {name:"Heartless",file:"heartless.mp3",statId:"#808_HL"},
    {name:"Amazing",file:"amazing.mp3",statId:"#808_AMAZ"},
    {name:"Love Lockdown",file:"love-lockdown.mp3",statId:"#808_LL"},
    {name:"Paranoid",file:"paranoid.mp3",statId:"#808_PAR"},
    {name:"RoboCop",file:"robocop.mp3",statId:"#808_RC"},
    {name:"Street Lights",file:"street-lights.mp3",statId:"#808_SL"},
    {name:"Bad News",file:"bad-news.mp3",statId:"#808_BN"},
    {name:"See You in My Nightmares",file:"see-you-in-my-nightmares.mp3",statId:"#808_SYMN"},
    {name:"Coldest Winter",file:"coldest-winter.mp3",statId:"#808_CW"},
    {name:"Pinocchio Story (Live)",file:"pinocchio-story.mp3",statId:"#808_PS"}
  ]
},
{
  id: "mbdtf",
  title: "My Beautiful Dark Twisted Fantasy",
  artist: "Kanye West",
  year: "2010",
  type: "official",
  tags: ["kanye","west","mbdtf","beautiful","dark","twisted","fantasy","runaway","power","rap","hip hop","2010"],
  cover: "https://i.scdn.co/image/ab67616d0000b273d9194aa18fa4c9362b47464f",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kanye-west/mbdtf/",
  tracks: [
    {name:"Dark Fantasy",file:"dark-fantasy.mp3",statId:"#MBDTF_DF"},
    {name:"Gorgeous",file:"gorgeous.mp3",statId:"#MBDTF_GOR"},
    {name:"POWER",file:"power.mp3",statId:"#MBDTF_PWR"},
    {name:"All of the Lights (Interlude)",file:"all-of-lights-interlude.mp3",statId:"#MBDTF_AOLI"},
    {name:"All of the Lights",file:"all-of-lights.mp3",statId:"#MBDTF_AOL"},
    {name:"Monster",file:"monster.mp3",statId:"#MBDTF_MON"},
    {name:"So Appalled",file:"so-appalled.mp3",statId:"#MBDTF_SA"},
    {name:"Devil in a New Dress",file:"devil-new-dress.mp3",statId:"#MBDTF_DIAND"},
    {name:"Runaway",file:"runaway.mp3",statId:"#MBDTF_RUN"},
    {name:"Hell of a Life",file:"hell-of-a-life.mp3",statId:"#MBDTF_HOAL"},
    {name:"Blame Game",file:"blame-game.mp3",statId:"#MBDTF_BG"},
    {name:"Lost in the World",file:"lost-in-the-world.mp3",statId:"#MBDTF_LITW"},
    {name:"Who Will Survive in America",file:"who-will-survive.mp3",statId:"#MBDTF_WWSIA"}
  ]
},
{
  id: "watch-throne",
  title: "Watch the Throne",
  artist: "JAŸ-Z",
  primaryArtist: "Kanye West",
  featuredArtists: ["Jay-Z"],
  year: "2011",
  type: "official",
  tags: ["kanye","west","jayz","watch","throne","niggas in paris","rap","hip hop","2011"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/e/ee/Watch_The_Throne.jpg/250px-Watch_The_Throne.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kanye-west/watch-the-throne/",
  tracks: [
    {name:"No Church in the Wild",file:"no-church.mp3",statId:"#WTT_NCITW"},
    {name:"Lift Off",file:"lift-off.mp3",statId:"#WTT_LO"},
    {name:"Niggas in Paris",file:"niggas-in-paris.mp3",statId:"#WTT_NIP"},
    {name:"Otis",file:"otis.mp3",statId:"#WTT_OTIS"},
    {name:"Gotta Have It",file:"gotta-have-it.mp3",statId:"#WTT_GHI"},
    {name:"New Day",file:"new-day.mp3",statId:"#WTT_ND"},
    {name:"That's My Bitch",file:"thats-my-bitch.mp3",statId:"#WTT_TMB"},
    {name:"Welcome to the Jungle",file:"welcome-jungle.mp3",statId:"#WTT_WTTJ"},
    {name:"Who Gon Stop Me",file:"who-gon-stop-me.mp3",statId:"#WTT_WGSM"},
    {name:"Murder to Excellence",file:"murder-excellence.mp3",statId:"#WTT_MTE"},
    {name:"Sweet Baby Jesus",file:"sweet-baby-jesus.mp3"},
    {name:"Why I Love You",file:"why-i-love-you.mp3",statId:"#WTT_WILY"},
    {name:"H•A•M",file:"ham.mp3",statId:"#WTT_HAM"},
    {name:"Primetime",file:"primetime.mp3",statId:"#WTT_PT"},
    {name:"The Joy",file:"the-joy.mp3",statId:"#WTT_TJ"}
  ]
},
{
  id: "cruel-summer",
  title: "Cruel Summer",
  artist: "GOOD Music",
  primaryArtist: "Kanye West",
  featuredArtists: ["Big Sean","2 Chainz","John Legend","Teyana Taylor"],
  year: "2012",
  type: "official",
  tags: ["kanye","west","good","music","cruel","summer","mercy","clique","rap","hip hop","2012"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/a/ab/CruelSummercover.jpg/250px-CruelSummercover.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kanye-west/cruel-summer/",
  tracks: [
    {name:"To the World",file:"to-the-world.mp3",statId:"#CS_TTW"},
    {name:"Mercy",file:"mercy.mp3",statId:"#CS_MERCY"},
    {name:"New God Flow",file:"new-god-flow.mp3",statId:"#CS_NGF"},
    {name:"Clique",file:"clique.mp3",statId:"#CS_CLIQUE"},
    {name:"Bliss",file:"bliss.mp3",statId:"#CS_BLISS"},
    {name:"Cruel Summer",file:"cruel-summer.mp3",statId:"#CS_CS"},
    {name:"Higher",file:"higher.mp3",statId:"#CS_HIGH"},
    {name:"Don't Like (Remix)",file:"dont-like.mp3",statId:"#CS_DL"},
    {name:"The Morning",file:"the-morning.mp3",statId:"#CS_TM"},
    {name:"Cold",file:"cold.mp3",statId:"#CS_COLD"},
    {name:"Sweet Baby Jesus",file:"sweet-baby-jesus.mp3",statId:"#CS_SBJ"},
    {name:"Sin City",file:"sin-city.mp3",statId:"#CS_SC"},
    {name:"Way Too Cold",file:"way-too-cold.mp3",statId:"#CS_WTC"},
    {name:"Creepers",file:"creepers.mp3",statId:"#CS_CREEP"}
  ]
},
{
  id: "yeezus",
  title: "Yeezus",
  artist: "Kanye West",
  year: "2013",
  type: "official",
  tags: ["kanye","west","yeezus","bound 2","new slaves","black skinhead","rap","industrial","2013"],
  cover: "https://m.media-amazon.com/images/I/516qybuOZhL._UF1000,1000_QL80_.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kanye-west/yeezus/",
  tracks: [
    {name:"On Sight",file:"on-sight.mp3",statId:"#YZ_OS"},
    {name:"Black Skinhead",file:"black-skinhead.mp3",statId:"#YZ_BSH"},
    {name:"I Am a God",file:"i-am-a-god.mp3",statId:"#YZ_IAAG"},
    {name:"New Slaves",file:"new-slaves.mp3",statId:"#YZ_NS"},
    {name:"Hold My Liquor",file:"hold-my-liquor.mp3",statId:"#YZ_HML"},
    {name:"I'm in It",file:"im-in-it.mp3",statId:"#YZ_III"},
    {name:"Blood on the Leaves",file:"blood-on-leaves.mp3",statId:"#YZ_BOTL"},
    {name:"Guilt Trip",file:"guilt-trip.mp3",statId:"#YZ_GT"},
    {name:"Send It Up",file:"send-it-up.mp3",statId:"#YZ_SIU"},
    {name:"Bound 2",file:"bound-2.mp3",statId:"#YZ_B2"}
  ]
},
{
  id: "tlop",
  title: "The Life of Pablo",
  artist: "Kanye West",
  year: "2016",
  type: "official",
  tags: ["kanye","west","pablo","tlop","ultralight beam","famous","fade","rap","gospel","2016"],
  cover: "https://preview.redd.it/puu7vsw10fb01.png?width=640&crop=smart&auto=webp&s=cef42bec02f7a6064349d8cfd34df097bfe12ade",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kanye-west/the-life-of-pablo/",
  tracks: [
    {name:"Ultralight Beam",file:"ultralight-beam.mp3",statId:"#TLOP_UB"},
    {name:"Father Stretch My Hands Pt. 1",file:"fsmh-pt1.mp3",statId:"#TLOP_FSMH1"},
    {name:"Pt. 2",file:"fsmh-pt2.mp3",statId:"#TLOP_FSMH2"},
    {name:"Famous",file:"famous.mp3",statId:"#TLOP_FAM"},
    {name:"Feedback",file:"feedback.mp3",statId:"#TLOP_FB"},
    {name:"Low Lights",file:"low-lights.mp3",statId:"#TLOP_LL"},
    {name:"Highlights",file:"highlights.mp3",statId:"#TLOP_HL"},
    {name:"Freestyle 4",file:"freestyle-4.mp3",statId:"#TLOP_F4"},
    {name:"I Love Kanye",file:"i-love-kanye.mp3",statId:"#TLOP_ILK"},
    {name:"Waves",file:"waves.mp3",statId:"#TLOP_WAV"},
    {name:"FML",file:"fml.mp3",statId:"#TLOP_FML"},
    {name:"Real Friends",file:"real-friends.mp3",statId:"#TLOP_RF"},
    {name:"Wolves",file:"wolves.mp3",statId:"#TLOP_WLV"},
    {name:"Frank's Track",file:"franks-track.mp3"},
    {name:"Siiiiiiiiilver Surfffter Surffffff",file:"silver-surfer.mp3",statId:"#TLOP_SS"},
    {name:"30 Hours",file:"30-hours.mp3",statId:"#TLOP_30H"},
    {name:"No More Parties in LA",file:"no-more-parties.mp3",statId:"#TLOP_NMPLA"},
    {name:"Facts (Charlie Heat Version)",file:"facts.mp3",statId:"#TLOP_FACTS"},
    {name:"Fade",file:"fade.mp3",statId:"#TLOP_FADE"},
    {name:"Saint Pablo",file:"saint-pablo.mp3",statId:"#TLOP_SP"}
  ]
},
{
  id: "ye",
  title: "ye",
  artist: "Kanye West",
  year: "2018",
  type: "official",
  tags: ["kanye","west","ye","yikes","ghost town","violent crimes","rap","2018"],
  cover: "https://upload.wikimedia.org/wikipedia/en/7/74/Ye_album_cover.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kanye-west/ye/",
  tracks: [
    {name:"I Thought About Killing You",file:"i-thought-about.mp3",statId:"#YE_ITAKY"},
    {name:"Yikes",file:"yikes.mp3",statId:"#YE_YK"},
    {name:"All Mine",file:"all-mine.mp3",statId:"#YE_AM"},
    {name:"Wouldn't Leave",file:"wouldnt-leave.mp3",statId:"#YE_WL"},
    {name:"No Mistakes",file:"no-mistakes.mp3",statId:"#YE_NM"},
    {name:"Ghost Town",file:"ghost-town.mp3",statId:"#YE_GT"},
    {name:"Violent Crimes",file:"violent-crimes.mp3",statId:"#YE_VC"}
  ]
},
{
  id: "kids-see-ghosts",
  title: "Kids See Ghosts",
  artist: "Kids See Ghosts",
  primaryArtist: "Kanye West",
  featuredArtists: ["Kid Cudi"],
  year: "2018",
  type: "official",
  tags: ["kanye","west","cudi","kids","see","ghosts","reborn","rap","2018"],
  cover: "https://upload.wikimedia.org/wikipedia/en/4/44/Kids_See_Ghosts_Cover.png",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kanye-west/kids-see-ghosts/",
  tracks: [
    {name:"Feel the Love",file:"feel-the-love.mp3",statId:"#KSG_FTL"},
    {name:"Fire",file:"fire.mp3",statId:"#KSG_FIRE"},
    {name:"4th Dimension",file:"4th-dimension.mp3",statId:"#KSG_4D"},
    {name:"Freeee (Ghost Town Pt. 2)",file:"freeee.mp3",statId:"#KSG_FREE"},
    {name:"Reborn",file:"reborn.mp3",statId:"#KSG_REB"},
    {name:"Kids See Ghosts",file:"kids-see-ghosts.mp3",statId:"#KSG_KSG"},
    {name:"Cudi Montage",file:"cudi-montage.mp3",statId:"#KSG_CM"}
  ]
},
{
  id: "jesus-is-king",
  title: "Jesus Is King",
  artist: "Kanye West",
  year: "2019",
  type: "official",
  tags: ["kanye","west","jesus","king","gospel","follow god","closed on sunday","rap","2019"],
  cover: "https://media.pitchfork.com/photos/5db73da8fd8a1f0009ad5c80/master/pass/jesusisking_kanye.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kanye-west/jesus-is-king/",
  tracks: [
    {name:"Every Hour",file:"every-hour.mp3",statId:"#JIK_EH"},
    {name:"Follow God",file:"follow-god.mp3",statId:"#JIK_FG"},
    {name:"Closed on Sunday",file:"closed-on-sunday.mp3",statId:"#JIK_COS"},
    {name:"On God",file:"on-god.mp3",statId:"#JIK_OG"},
    {name:"Everything We Need",file:"everything-we-need.mp3",statId:"#JIK_EWN"},
    {name:"Water",file:"water.mp3",statId:"#JIK_WAT"},
    {name:"God Is",file:"god-is.mp3",statId:"#JIK_GI"},
    {name:"Hands On",file:"hands-on.mp3",statId:"#JIK_HO"},
    {name:"Use This Gospel",file:"use-this-gospel.mp3",statId:"#JIK_UTG"},
    {name:"Jesus Is Lord",file:"jesus-is-lord.mp3",statId:"#JIK_JIL"}
  ]
},
{
  id: "donda",
  title: "Donda",
  artist: "Kanye West",
  year: "2021",
  type: "official",
  tags: ["kanye","west","donda","off the grid","hurricane","praise god","jail","rap","gospel","2021"],
  cover: "https://i.redd.it/jvst2ity53d51.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kanye-west/donda/",
  tracks: [
    {name:"Donda Chant",file:"donda-chant.mp3",statId:"#DON_DC"},
    {name:"Jail",file:"jail.mp3",statId:"#DON_JAIL"},
    {name:"God Breathed",file:"god-breathed.mp3",statId:"#DON_GB"},
    {name:"Off the Grid",file:"off-the-grid.mp3",statId:"#DON_OTG"},
    {name:"Hurricane",file:"hurricane.mp3",statId:"#DON_HUR"},
    {name:"Praise God",file:"praise-god.mp3",statId:"#DON_PG"},
    {name:"Jonah",file:"jonah.mp3",statId:"#DON_JON"},
    {name:"Ok Ok",file:"ok-ok.mp3",statId:"#DON_OO"},
    {name:"Junya",file:"junya.mp3",statId:"#DON_JUN"},
    {name:"Believe What I Say",file:"believe-what-i-say.mp3",statId:"#DON_BWIS"},
    {name:"24",file:"24.mp3",statId:"#DON_24"},
    {name:"Remote Control",file:"remote-control.mp3",statId:"#DON_RC"},
    {name:"Moon",file:"moon.mp3",statId:"#DON_MOON"},
    {name:"Heaven and Hell",file:"heaven-and-hell.mp3",statId:"#DON_HAH"},
    {name:"Donda",file:"donda-title.mp3",statId:"#DON_DON"},
    {name:"Pure Souls",file:"pure-souls.mp3",statId:"#DON_PS"},
    {name:"Come to Life",file:"come-to-life.mp3",statId:"#DON_CTL"},
    {name:"No Child Left Behind",file:"no-child.mp3",statId:"#DON_NCLB"},
    {name:"Jail pt 2",file:"jail-pt2.mp3",statId:"#DON_JAIL2"},
    {name:"Jesus Lord",file:"jesus-lord.mp3",statId:"#DON_JL"},
    {name:"New Again",file:"new-again.mp3",statId:"#DON_NA"},
    {name:"Tell the Vision",file:"tell-the-vision.mp3",statId:"#DON_TTV"},
    {name:"Lord I Need You",file:"lord-i-need-you.mp3",statId:"#DON_LINY"},
    {name:"Jail pt 3",file:"jail-pt3.mp3"}
  ]
},
{
  id: "donda-2",
  title: "Donda 2",
  artist: "Kanye West",
  year: "2022",
  type: "official",
  tags: ["kanye","west","donda","2","stem player","rap","2022"],
  cover: "https://i.scdn.co/image/ab67616d0000b2736dc675e2b4f4d86b762f3bfa",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kanye-west/donda-2/",
  tracks: [
    {name:"Sci Fi",file:"sci-fi.mp3",statId:"#D2_SF"},
    {name:"True Love",file:"true-love.mp3",statId:"#D2_TL"},
    {name:"Security",file:"security.mp3",statId:"#D2_SEC"},
    {name:"Too Easy",file:"too-easy.mp3",statId:"#D2_TE"},
    {name:"Louie Bags",file:"louie-bags.mp3",statId:"#D2_LB"},
    {name:"Pablo",file:"pablo.mp3",statId:"#D2_PAB"},
    {name:"Rich Flex",file:"rich-flex.mp3",statId:"#D2_RF"},
    {name:"Happy",file:"happy.mp3",statId:"#D2_HAP"},
    {name:"We Did It Kid",file:"we-did-it-kid.mp3",statId:"#D2_WDIK"},
    {name:"Flowers",file:"flowers.mp3",statId:"#D2_FLW"}
  ]
},
{
  id: "vultures-1",
  title: "Vultures 1",
  artist: "¥$",
  primaryArtist: "Kanye West",
  featuredArtists: ["Ty Dolla $ign"],
  year: "2024",
  type: "official",
  tags: ["kanye","west","ty dolla sign","vultures","carnival","hoodrat","rap","2024"],
  cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Kanye_West_and_Ty_Dolla_Sign_-_Vultures_Vol._1_%28Cover%29.png/250px-Kanye_West_and_Ty_Dolla_Sign_-_Vultures_Vol._1_%28Cover%29.png",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kanye-west/vultures-1/",
  tracks: [
    {name:"Vultures",file:"vultures-title.mp3",statId:"#V1_VUL"},
    {name:"Paid",file:"paid.mp3",statId:"#V1_PAID"},
    {name:"Hoodrat",file:"hoodrat.mp3",statId:"#V1_HR"},
    {name:"Talking",file:"talking.mp3",statId:"#V1_TALK"},
    {name:"Carnival",file:"carnival.mp3",statId:"#V1_CARN"},
    {name:"Burn",file:"burn.mp3",statId:"#V1_BURN"},
    {name:"King",file:"king.mp3",statId:"#V1_KING"},
    {name:"Keys to My Life",file:"keys-to-my-life.mp3",statId:"#V1_KTML"},
    {name:"FML (feat. The Weeknd)",file:"fml.mp3"},
    {name:"Problematic",file:"problematic.mp3",statId:"#V1_PROB"},
    {name:"Good (Don't Die)",file:"good-dont-die.mp3",statId:"#V1_GDD"},
    {name:"Do It",file:"do-it.mp3",statId:"#V1_DI"},
    {name:"Beg Forgiveness",file:"beg-forgiveness.mp3",statId:"#V1_BF"},
    {name:"Paperwork",file:"paperwork.mp3",statId:"#V1_PW"},
    {name:"Back to Me",file:"back-to-me.mp3",statId:"#V1_BTM"},
    {name:"Vultures 2",file:"vultures-2-track.mp3",statId:"#V1_V2"},
    {name:"Lifestyle",file:"lifestyle.mp3",statId:"#V1_LS"}
  ]
},
{
  id: "vultures-2",
  title: "Vultures 2",
  artist: "¥$",
  primaryArtist: "Kanye West",
  featuredArtists: ["Ty Dolla $ign"],
  year: "2024",
  type: "official",
  tags: ["kanye","west","ty dolla sign","vultures","2","rap","2024"],
  cover: "https://images.genius.com/8e2c3c0e076e066fa40966001b956663.1000x1000x1.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kanye-west/vultures-2/",
  tracks: [
    {name:"Field Trip",file:"field-trip.mp3",statId:"#V2_FT"},
    {name:"Everybody",file:"everybody.mp3",statId:"#V2_EVB"},
    {name:"Bomb",file:"bomb.mp3",statId:"#V2_BOMB"},
    {name:"River",file:"river.mp3",statId:"#V2_RIV"},
    {name:"Science",file:"science.mp3",statId:"#V2_SCI"},
    {name:"Munch",file:"munch.mp3",statId:"#V2_MUNCH"},
    {name:"Drive",file:"drive.mp3",statId:"#V2_DRV"},
    {name:"Mast",file:"mast.mp3",statId:"#V2_MAST"},
    {name:"Beg",file:"beg.mp3",statId:"#V2_BEG"},
    {name:"Lonely Roads",file:"lonely-roads.mp3",statId:"#V2_LR"},
    {name:"Gun To My Head",file:"gun-to-my-head.mp3",statId:"#V2_GTMH"},
    {name:"Preacher Man",file:"preacher-man.mp3",statId:"#V2_PM"},
    {name:"Slide",file:"slide.mp3",statId:"#V2_SLD"},
    {name:"Fvcking Demons",file:"fvcking-demons.mp3",statId:"#V2_FD"}
  ]
},
{
  id: "bully",
  title: "Bully",
  artist: "Kanye West",
  year: "2025",
  type: "official",
  tags: ["kanye","west","ye","bully","rap","2025"],
  cover: "https://news.artnet.com/app/news-upload/2024/10/kanye-west-bully-ye.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kanye-west/bully/",
  tracks: [
    {name:"Bully",file:"bully-title.mp3",statId:"#BUL_BUL"},
    {name:"Lonely",file:"lonely.mp3",statId:"#BUL_LON"},
    {name:"Industry",file:"industry.mp3",statId:"#BUL_IND"},
    {name:"Witches",file:"witches.mp3",statId:"#BUL_WIT"},
    {name:"Field Trip",file:"field-trip.mp3"},
    {name:"New Body",file:"new-body.mp3",statId:"#BUL_NB"},
    {name:"Hard Way",file:"hard-way.mp3",statId:"#BUL_HW"},
    {name:"Forever",file:"forever.mp3",statId:"#BUL_FOR"},
    {name:"Champion 2",file:"champion-2.mp3",statId:"#BUL_C2"},
    {name:"Empire",file:"empire.mp3",statId:"#BUL_EMP"}
  ]
},

// ─── PLAYBOI CARTI ────────────────────────────────────
{
  id: "die-lit",
  title: "Die Lit",
  artist: "Playboi Carti",
  year: "2018",
  type: "official",
  tags: ["playboi carti","rap","2018"],
  cover: "https://upload.wikimedia.org/wikipedia/en/c/c6/Die_Lit_by_Playboi_Carti.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/playboi-carti/die-lit/",
  tracks: [
    {name:"Long Time (Intro)",file:"long-time.mp3",statId:"#DL_LT"},
    {name:"R.I.P.",file:"rip.mp3",statId:"#DL_RIP"},
    {name:"Lean 4 Real (feat. Skepta)",file:"lean-4-real.mp3",statId:"#DL_L4R"},
    {name:"Old Money",file:"old-money.mp3",statId:"#DL_OM"},
    {name:"Love Hurts (feat. Travis Scott)",file:"love-hurts.mp3",statId:"#DL_LH"},
    {name:"Shoota (feat. Lil Uzi Vert)",file:"shoota.mp3",statId:"#DL_SHOOT"},
    {name:"Right Now (feat. Pi'erre Bourne)",file:"right-now.mp3",statId:"#DL_RN"},
    {name:"Poke It Out (feat. Nicki Minaj)",file:"poke-it-out.mp3",statId:"#DL_PIO"},
    {name:"Home (KOD)",file:"home-kod.mp3",statId:"#DL_HOME"},
    {name:"Fell In Luv (feat. Bryson Tiller)",file:"fell-in-luv.mp3",statId:"#DL_FIL"},
    {name:"Foreign",file:"foreign.mp3",statId:"#DL_FOR"},
    {name:"Pull Up",file:"pull-up.mp3",statId:"#DL_PU"},
    {name:"Mileage (feat. Chief Keef)",file:"mileage.mp3",statId:"#DL_MIL"},
    {name:"FlatBed Freestyle",file:"flatbed-freestyle.mp3",statId:"#DL_FF"},
    {name:"No Time (feat. Gunna)",file:"no-time.mp3",statId:"#DL_NT"},
    {name:"Middle of the Summer (feat. Red Coldhearted)",file:"middle-of-the-summer.mp3",statId:"#DL_MOTS"},
    {name:"Choppa Won't Miss (feat. Young Thug)",file:"choppa-wont-miss.mp3",statId:"#DL_CWM"},
    {name:"R.I.P. Fredo (Notice Me) (feat. Young Nudy)",file:"rip-fredo.mp3",statId:"#DL_RIPF"},
    {name:"Top (feat. Pi'erre Bourne)",file:"top.mp3",statId:"#DL_TOP"}
  ]
},

// ─── TYLER, THE CREATOR ───────────────────────────────
{
  id: "goblin",
  title: "Goblin",
  artist: "Tyler, the Creator",
  year: "2011",
  type: "official",
  tags: ["tyler the creator","rap","2011"],
  cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/goblin/covers/IMG_6377.jpeg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/tyler-the-creator/goblin/",
  tracks: [
    {name:"Goblin",file:"goblin.mp3",statId:"#GOB_GOB"},
    {name:"Yonkers",file:"yonkers.mp3",statId:"#GOB_YON"},
    {name:"Radicals",file:"radicals.mp3",statId:"#GOB_RAD"},
    {name:"She (feat. Frank Ocean)",file:"she.mp3",statId:"#GOB_SHE"},
    {name:"Transylvania",file:"transylvania.mp3",statId:"#GOB_TRANS"},
    {name:"Nightmare",file:"nightmare.mp3",statId:"#GOB_NIGHT"},
    {name:"Tron Cat",file:"tron-cat.mp3",statId:"#GOB_TC"},
    {name:"Her",file:"her.mp3",statId:"#GOB_HER"},
    {name:"Sandwitches (feat. Hodgy)",file:"sandwitches.mp3",statId:"#GOB_SAND"},
    {name:"Fish",file:"fish.mp3",statId:"#GOB_FISH"},
    {name:"Analog (feat. Hodgy)",file:"analog.mp3",statId:"#GOB_ANA"},
    {name:"B.S.D.",file:"bsd.mp3",statId:"#GOB_BSD"},
    {name:"Window (feat. Domo Genesis, Hodgy & Mike G)",file:"window.mp3",statId:"#GOB_WIN"},
    {name:"AU79",file:"au79.mp3",statId:"#GOB_AU79"},
    {name:"Golden",file:"golden.mp3",statId:"#GOB_GOLD"}
  ]
},
{
  id: "wolf",
  title: "Wolf",
  artist: "Tyler, the Creator",
  year: "2013",
  type: "official",
  tags: ["tyler the creator","rap","2013"],
  cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/wolf/covers/IMG_6378.jpeg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/tyler-the-creator/wolf/",
  tracks: [
    {name:"Wolf",file:"wolf.mp3",statId:"#WOLF_WOLF"},
    {name:"Jamba (feat. Hodgy)",file:"jamba.mp3",statId:"#WOLF_JAM"},
    {name:"Cowboy",file:"cowboy.mp3",statId:"#WOLF_COW"},
    {name:"Awkward",file:"awkward.mp3",statId:"#WOLF_AWK"},
    {name:"Domo23",file:"domo23.mp3",statId:"#WOLF_D23"},
    {name:"Answer",file:"answer.mp3",statId:"#WOLF_ANS"},
    {name:"Slater (feat. Frank Ocean)",file:"slater.mp3",statId:"#WOLF_SLA"},
    {name:"48",file:"48.mp3",statId:"#WOLF_48"},
    {name:"Colossus",file:"colossus.mp3",statId:"#WOLF_COL"},
    {name:"PartyIsntOver/Campfire/Bimmer (feat. Frank Ocean & Lætitia Sadier)",file:"piocb.mp3",statId:"#WOLF_PCB"},
    {name:"IFHY (feat. Pharrell)",file:"ifhy.mp3",statId:"#WOLF_IFHY"},
    {name:"Pigs",file:"pigs.mp3",statId:"#WOLF_PIGS"},
    {name:"Parking Lot (feat. Mike G & Casey Veggies)",file:"parking-lot.mp3",statId:"#WOLF_PL"},
    {name:"Rusty (feat. Domo Genesis & Earl Sweatshirt)",file:"rusty.mp3",statId:"#WOLF_RUS"},
    {name:"Trashwang (feat. Odd Future)",file:"trashwang.mp3",statId:"#WOLF_TW"},
    {name:"Treehome95 (feat. Coco O. & Erykah Badu)",file:"treehome95.mp3",statId:"#WOLF_TH95"},
    {name:"Tamale",file:"tamale.mp3",statId:"#WOLF_TAM"},
    {name:"Lone",file:"lone.mp3",statId:"#WOLF_LONE"}
  ]
},
{
  id: "cherry-bomb",
  title: "Cherry Bomb",
  artist: "Tyler, the Creator",
  year: "2015",
  type: "official",
  tags: ["tyler the creator","rap","2015"],
  cover: "https://preview.redd.it/qubhiqn6zrs51.jpg?width=640&crop=smart&auto=webp&s=a4129b25a29105c59a9a9ea5d866ae8cd8f2915d",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/tyler-the-creator/cherry-bomb/",
  tracks: [
    {name:"Deathcamp",file:"deathcamp.mp3",statId:"#CB_DC"},
    {name:"Buffalo",file:"buffalo.mp3",statId:"#CB_BUF"},
    {name:"Pilot",file:"pilot.mp3",statId:"#CB_PIL"},
    {name:"Run",file:"run.mp3",statId:"#CB_RUN"},
    {name:"Find Your Wings (feat. Kali Uchis & Roy Ayers)",file:"find-your-wings.mp3",statId:"#CB_FYW"},
    {name:"Cherry Bomb",file:"cherry-bomb.mp3",statId:"#CB_CB"},
    {name:"Blow My Load (feat. Wanya Morris, Dâm-Funk & Austin Feinstein)",file:"blow-my-load.mp3",statId:"#CB_BML"},
    {name:"2SEATER (feat. Aaron Shaw & Samantha Nelson)",file:"2seater.mp3",statId:"#CB_2S"},
    {name:"The Brown Stains of Darkeese Latifah Part 6–12 (Remix) (feat. Schoolboy Q)",file:"brown-stains.mp3",statId:"#CB_BS"},
    {name:"Fucking Young / Perfect (feat. Charlie Wilson, Kali Uchis & Austin Feinstein)",file:"fucking-young-perfect.mp3",statId:"#CB_FYP"},
    {name:"Smuckers (feat. Kanye West & Lil Wayne)",file:"smuckers.mp3",statId:"#CB_SMU"},
    {name:"Keep Da O's (feat. Pharrell & Coco O.)",file:"keep-da-os.mp3",statId:"#CB_KDO"},
    {name:"Okaga, CA",file:"okaga-ca.mp3",statId:"#CB_OKA"}
  ]
},
{
  id: "flower-boy",
  title: "Flower Boy",
  artist: "Tyler, the Creator",
  year: "2017",
  type: "official",
  tags: ["tyler the creator","rap","2017"],
  cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/flowerboy/covers/IMG_6382.jpeg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/tyler-the-creator/flower-boy/",
  tracks: [
    {name:"Foreword (feat. Rex Orange County)",file:"foreword.mp3",statId:"#FB_FORE"},
    {name:"Where This Flower Blooms (feat. Frank Ocean)",file:"where-this-flower-blooms.mp3",statId:"#FB_WTFB"},
    {name:"Sometimes...",file:"sometimes.mp3",statId:"#FB_SOM"},
    {name:"See You Again (feat. Kali Uchis)",file:"see-you-again.mp3",statId:"#FB_SYA"},
    {name:"Who Dat Boy (feat. A$AP Rocky)",file:"who-dat-boy.mp3",statId:"#FB_WDB"},
    {name:"Pothole (feat. Jaden Smith)",file:"pothole.mp3",statId:"#FB_POT"},
    {name:"Garden Shed (feat. Estelle)",file:"garden-shed.mp3",statId:"#FB_GS"},
    {name:"Boredom (feat. Rex Orange County & Anna of the North)",file:"boredom.mp3",statId:"#FB_BOR"},
    {name:"I Ain't Got Time!",file:"i-aint-got-time.mp3",statId:"#FB_IAGT"},
    {name:"911 / Mr. Lonely (feat. Frank Ocean & Steve Lacy)",file:"911-mr-lonely.mp3",statId:"#FB_911"},
    {name:"Droppin' Seeds (feat. Lil Wayne)",file:"droppin-seeds.mp3",statId:"#FB_DS"},
    {name:"November",file:"november.mp3",statId:"#FB_NOV"},
    {name:"Glitter",file:"glitter.mp3",statId:"#FB_GLI"},
    {name:"Enjoy Right Now, Today",file:"enjoy-right-now-today.mp3",statId:"#FB_ERNT"}
  ]
},
{
  id: "igor",
  title: "IGOR",
  artist: "Tyler, the Creator",
  year: "2019",
  type: "official",
  tags: ["tyler the creator","rap","2019","alternative hip hop"],
  cover: "https://upload.wikimedia.org/wikipedia/en/5/51/Igor_-_Tyler%2C_the_Creator.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/tyler-the-creator/igor/",
  tracks: [
    {name:"IGOR'S THEME",file:"igors-theme.mp3",statId:"#IGOR_IT"},
    {name:"EARFQUAKE",file:"earfquake.mp3",statId:"#IGOR_EQ"},
    {name:"I THINK",file:"i-think.mp3",statId:"#IGOR_ITK"},
    {name:"EXACTLY WHAT YOU RUN FROM YOU END UP CHASING",file:"exactly-what-you-run-from.mp3",statId:"#IGOR_EWYRF"},
    {name:"RUNNING OUT OF TIME",file:"running-out-of-time.mp3",statId:"#IGOR_ROOT"},
    {name:"NEW MAGIC WAND",file:"new-magic-wand.mp3",statId:"#IGOR_NMW"},
    {name:"A BOY IS A GUN*",file:"a-boy-is-a-gun.mp3",statId:"#IGOR_ABIAG"},
    {name:"PUPPET",file:"puppet.mp3",statId:"#IGOR_PUP"},
    {name:"WHAT'S GOOD",file:"whats-good.mp3",statId:"#IGOR_WG"},
    {name:"GONE, GONE / THANK YOU",file:"gone-gone-thank-you.mp3",statId:"#IGOR_GGTY"},
    {name:"I DON'T LOVE YOU ANYMORE",file:"idlya.mp3",statId:"#IGOR_IDLYA"},
    {name:"ARE WE STILL FRIENDS?",file:"are-we-still-friends.mp3",statId:"#IGOR_AWSF"}
  ]
},
{
  id: "cmiygl",
  title: "CALL ME IF YOU GET LOST",
  artist: "Tyler, the Creator",
  year: "2021",
  type: "official",
  tags: ["tyler the creator","rap","2021"],
  cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/cmiygl/covers/IMG_6383.jpeg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/tyler-the-creator/cmiygl/",
  tracks: [
    {name:"SIR BAUDELAIRE (feat. DJ Drama)",file:"sir-baudelaire.mp3",statId:"#CMIYGL_SB"},
    {name:"CORSO",file:"corso.mp3",statId:"#CMIYGL_COR"},
    {name:"LEMONHEAD (feat. 42 Dugg)",file:"lemonhead.mp3",statId:"#CMIYGL_LEM"},
    {name:"WUSYANAME (feat. YoungBoy Never Broke Again & Ty Dolla $ign)",file:"wusyaname.mp3",statId:"#CMIYGL_WUS"},
    {name:"LUMBERJACK",file:"lumberjack.mp3",statId:"#CMIYGL_LUM"},
    {name:"HOT WIND BLOWS (feat. Lil Wayne)",file:"hot-wind-blows.mp3",statId:"#CMIYGL_HWB"},
    {name:"MASSA",file:"massa.mp3",statId:"#CMIYGL_MAS"},
    {name:"RUNITUP (feat. Teezo Touchdown)",file:"runitup.mp3",statId:"#CMIYGL_RUN"},
    {name:"MANIFESTO (feat. Domo Genesis)",file:"manifesto.mp3",statId:"#CMIYGL_MAN"},
    {name:"SWEET / I THOUGHT YOU WANTED TO DANCE (feat. Brent Faiyaz & Fana Hues)",file:"sweet-itywtd.mp3",statId:"#CMIYGL_SWE"},
    {name:"MOMMA TALK",file:"momma-talk.mp3",statId:"#CMIYGL_MT"},
    {name:"RISE! (feat. Daisy World)",file:"rise.mp3",statId:"#CMIYGL_RISE"},
    {name:"BLESSED",file:"blessed.mp3",statId:"#CMIYGL_BLE"},
    {name:"JUGGERNAUT (feat. Lil Uzi Vert & Pharrell Williams)",file:"juggernaut.mp3",statId:"#CMIYGL_JUG"},
    {name:"WILSHIRE",file:"wilshire.mp3",statId:"#CMIYGL_WIL"},
    {name:"SAFARI",file:"safari.mp3",statId:"#CMIYGL_SAF"}
  ]
},
{
  id: "cmiygl-deluxe",
  title: "CALL ME IF YOU GET LOST: The Estate Sale",
  artist: "Tyler, the Creator",
  year: "2023",
  type: "official",
  tags: ["tyler the creator","rap","2023","deluxe"],
  cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/cmiygl_the-estate-sale/covers/IMG_6384.jpeg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/tyler-the-creator/cmiygl-the-estate-sale/",
  tracks: [
    {name:"EVERYTHING MUST GO (feat. DJ Drama)",file:"everything-must-go.mp3",statId:"#TES_EMG"},
    {name:"STUNTMAN (feat. Vince Staples)",file:"stuntman.mp3",statId:"#TES_STU"},
    {name:"WHAT A DAY",file:"what-a-day.mp3",statId:"#TES_WAD"},
    {name:"WHARF TALK (feat. A$AP Rocky)",file:"wharf-talk.mp3",statId:"#TES_WT"},
    {name:"DOGTOOTH",file:"dogtooth.mp3",statId:"#TES_DOG"},
    {name:"HEAVEN TO ME",file:"heaven-to-me.mp3",statId:"#TES_HTM"},
    {name:"BOYFRIEND, GIRLFRIEND (2020 Demo) (feat. YG)",file:"boyfriend-girlfriend.mp3",statId:"#TES_BG"}
  ]
},
{
  id: "chromakopia",
  title: "CHROMAKOPIA",
  artist: "Tyler, the Creator",
  year: "2024",
  type: "official",
  tags: ["tyler the creator","rap","2024"],
  cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/chromakopia/covers/IMG_6385.webp",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/tyler-the-creator/chromakopia/",
  tracks: [
    {name:"ST. CHROMA",file:"st-chroma.mp3",statId:"#CHK_SC"},
    {name:"NOID",file:"noid.mp3",statId:"#CHK_NOID"},
    {name:"I KILLED YOU",file:"i-killed-you.mp3",statId:"#CHK_IKY"},
    {name:"THOUGHT I WAS DEAD",file:"thought-i-was-dead.mp3",statId:"#CHK_TWD"},
    {name:"LIKE HIM",file:"like-him.mp3",statId:"#CHK_LH"},
    {name:"DARLING, I",file:"darling-i.mp3",statId:"#CHK_DI"},
    {name:"HEY JANE",file:"hey-jane.mp3",statId:"#CHK_HJ"},
    {name:"BALLOON",file:"balloon.mp3",statId:"#CHK_BAL"},
    {name:"LOVE, PEACE, AND LIGHT",file:"love-peace-light.mp3",statId:"#CHK_LPL"},
    {name:"WELCOME TO THE DISCO",file:"welcome-to-the-disco.mp3",statId:"#CHK_WTD"},
    {name:"ELECTRIC RAINBOW",file:"electric-rainbow.mp3",statId:"#CHK_ER"},
    {name:"FANTASY",file:"fantasy.mp3",statId:"#CHK_FAN"},
    {name:"CHROMAKOPIA (Outro)",file:"chromakopia-outro.mp3",statId:"#CHK_OUT"}
  ]
},
{
  id: "dont-tap-the-glass",
  title: "DON'T TAP THE GLASS",
  artist: "Tyler, the Creator",
  year: "2025",
  type: "official",
  tags: ["tyler the creator","rap","2025"],
  cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/dont-tap-the-glass/covers/Untitled174_20260225160356.png",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/tyler-the-creator/dont-tap-the-glass/",
  tracks: [
    {name:"Big Poe (feat. Sk8brd)",file:"big-poe.mp3",statId:"#DTTG_BP"},
    {name:"Sugar On My Tongue",file:"sugar-on-my-tongue.mp3",statId:"#DTTG_SOT"},
    {name:"Sucka Free",file:"sucka-free.mp3",statId:"#DTTG_SF"},
    {name:"Mommanem",file:"mommanem.mp3",statId:"#DTTG_MOM"},
    {name:"Stop Playing With Me",file:"stop-playing-with-me.mp3",statId:"#DTTG_SPWM"},
    {name:"Ring Ring Ring",file:"ring-ring-ring.mp3",statId:"#DTTG_RRR"},
    {name:"Don't Tap That Glass / Tweakin'",file:"dont-tap-that-glass-tweakin.mp3",statId:"#DTTG_DTT"},
    {name:"Don't You Worry Baby",file:"dont-you-worry-baby.mp3",statId:"#DTTG_DYWB"},
    {name:"I'll Take Care of You",file:"ill-take-care-of-you.mp3",statId:"#DTTG_ITCOY"},
    {name:"Tell Me What It Is",file:"tell-me-what-it-is.mp3",statId:"#DTTG_TMWII"}
  ]
},

// ─── KENDRICK LAMAR ───────────────────────────────────
{
  id: "section-80",
  title: "Section.80",
  artist: "Kendrick Lamar",
  year: "2011",
  type: "official",
  tags: ["kendrick lamar","rap","2011","conscious hip hop"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/4/48/Section.80-Cover.jpg/250px-Section.80-Cover.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kendrick-lamar/section-80/",
  tracks: [
    {name:"Fuck Your Ethnicity",file:"fuck-your-ethnicity.mp3",statId:"#S80_FYE"},
    {name:"Hol' Up",file:"hol-up.mp3",statId:"#S80_HU"},
    {name:"A.D.H.D",file:"adhd.mp3",statId:"#S80_ADHD"},
    {name:"No Make-Up (Her Vice) (feat. Colin Munroe)",file:"no-makeup.mp3",statId:"#S80_NMU"},
    {name:"Tammy's Song (Her Evils)",file:"tammys-song.mp3",statId:"#S80_TS"},
    {name:"Chapter Six",file:"chapter-six.mp3",statId:"#S80_C6"},
    {name:"Ronald Reagan Era (His Evils)",file:"ronald-reagan-era.mp3",statId:"#S80_RRE"},
    {name:"Poe Man's Dreams (His Vice) (feat. GLC)",file:"poe-mans-dreams.mp3",statId:"#S80_PMD"},
    {name:"The Spiteful Chant (feat. Schoolboy Q)",file:"the-spiteful-chant.mp3",statId:"#S80_TSC"},
    {name:"Chapter Ten",file:"chapter-ten.mp3",statId:"#S80_C10"},
    {name:"Keisha's Song (Her Pain) (feat. Ashtrobot)",file:"keishas-song.mp3",statId:"#S80_KS"},
    {name:"Rigamortus",file:"rigamortus.mp3",statId:"#S80_RIG"},
    {name:"Kush & Corinthians (His Pain) (feat. BJ the Chicago Kid)",file:"kush-corinthians.mp3",statId:"#S80_KC"},
    {name:"Blow My High (Members Only)",file:"blow-my-high.mp3",statId:"#S80_BMH"},
    {name:"Ab-Soul's Outro (feat. Ab-Soul)",file:"ab-souls-outro.mp3",statId:"#S80_ASO"},
    {name:"HiiiPower",file:"hiiipower.mp3",statId:"#S80_HP"}
  ]
},
{
  id: "good-kid-maad-city",
  title: "good kid, m.A.A.d city",
  artist: "Kendrick Lamar",
  year: "2012",
  type: "official",
  tags: ["kendrick lamar","rap","2012","west coast hip hop"],
  cover: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgFRLKqN8J5PnVQaBUTENfIWH9W72_qInvDA&s",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kendrick-lamar/good-kid-maad-city/",
  tracks: [
    {name:"Sherane a.k.a Master Splinter's Daughter",file:"sherane.mp3",statId:"#GKMC_S"},
    {name:"Bitch, Don't Kill My Vibe",file:"bdkmv.mp3",statId:"#GKMC_BDKMV"},
    {name:"Backseat Freestyle",file:"backseat-freestyle.mp3",statId:"#GKMC_BF"},
    {name:"The Art of Peer Pressure",file:"art-of-peer-pressure.mp3",statId:"#GKMC_AOPP"},
    {name:"Money Trees (feat. Jay Rock)",file:"money-trees.mp3",statId:"#GKMC_MT"},
    {name:"Poetic Justice (feat. Drake)",file:"poetic-justice.mp3",statId:"#GKMC_PJ"},
    {name:"good kid",file:"good-kid.mp3",statId:"#GKMC_GK"},
    {name:"m.A.A.d city (feat. MC Eiht)",file:"maad-city.mp3",statId:"#GKMC_MC"},
    {name:"Swimming Pools (Drank)",file:"swimming-pools.mp3",statId:"#GKMC_SP"},
    {name:"Sing About Me, I'm Dying of Thirst",file:"samidot.mp3",statId:"#GKMC_SAM"},
    {name:"Real (feat. Anna Wise)",file:"real.mp3",statId:"#GKMC_REAL"},
    {name:"Compton (feat. Dr. Dre)",file:"compton.mp3",statId:"#GKMC_COMP"}
  ]
},
{
  id: "to-pimp-a-butterfly",
  title: "To Pimp a Butterfly",
  artist: "Kendrick Lamar",
  year: "2015",
  type: "official",
  tags: ["kendrick lamar","rap","2015","jazz rap"],
  cover: "https://upload.wikimedia.org/wikipedia/en/f/f6/Kendrick_Lamar_-_To_Pimp_a_Butterfly.png",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kendrick-lamar/to-pimp-a-butterfly/",
  tracks: [
    {name:"Wesley's Theory (feat. George Clinton & Thundercat)",file:"wesleys-theory.mp3",statId:"#TPAB_WT"},
    {name:"For Free? (Interlude)",file:"for-free.mp3",statId:"#TPAB_FF"},
    {name:"King Kunta",file:"king-kunta.mp3",statId:"#TPAB_KK"},
    {name:"Institutionalized",file:"institutionalized.mp3",statId:"#TPAB_INST"},
    {name:"These Walls",file:"these-walls.mp3",statId:"#TPAB_TW"},
    {name:"u",file:"u.mp3",statId:"#TPAB_U"},
    {name:"Alright",file:"alright.mp3",statId:"#TPAB_ALR"},
    {name:"Mortal Man",file:"mortal-man.mp3",statId:"#TPAB_MM"}
  ]
},
{
  id: "damn",
  title: "DAMN.",
  artist: "Kendrick Lamar",
  year: "2017",
  type: "official",
  tags: ["kendrick lamar","rap","2017"],
  cover: "https://external-preview.redd.it/7x4J7CpDkmARyvMW94fO6hSU2ohEztso2jzO37emeR8.jpg?auto=webp&s=cfc96f803045b54357f0824e59a3dd83aeec0389",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kendrick-lamar/damn/",
  tracks: [
    {name:"BLOOD.",file:"blood.mp3",statId:"#DAMN_BLOOD"},
    {name:"DNA.",file:"dna.mp3",statId:"#DAMN_DNA"},
    {name:"HUMBLE.",file:"humble.mp3",statId:"#DAMN_HUMBLE"},
    {name:"DUCKWORTH.",file:"duckworth.mp3",statId:"#DAMN_DUCK"}
  ]
},

// ─── LIL UZI VERT ─────────────────────────────────────
{
  id: "luv_is_rage",
  title: "Luv Is Rage",
  artist: "Lil Uzi Vert",
  year: "2015",
  type: "official",
  tags: ["lil uzi vert","rap","2015"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/5/54/Luv_Is_Rage_Cover.jpg/250px-Luv_Is_Rage_Cover.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/lil-uzi-vert/luv-is-rage/",
  tracks: [
    {name:"Safe House",file:"safe_house.mp3",statId:"#LIR_SAFE_HOUSE"},
    {name:"Enemies",file:"enemies.mp3",statId:"#LIR_ENEMIES"},
    {name:"Want Some More",file:"want_some_more.mp3",statId:"#LIR_WSM"},
    {name:"Right Now",file:"right_now.mp3",statId:"#LIR_RIGHT_NOW"},
    {name:"All My Chains",file:"all_my_chains.mp3",statId:"#LIR_AMC"},
    {name:"Nuyork Nights at 21",file:"nuyork_nights.mp3",statId:"#LIR_NNY21"},
    {name:"Yamborghini Dream",file:"yamborghini_dream.mp3",statId:"#LIR_YAMB"},
    {name:"Bleed",file:"bleed.mp3",statId:"#LIR_BLEED"},
    {name:"Luv Is Rage",file:"luv_is_rage.mp3",statId:"#LIR_TITLE"}
  ]
},
{
  id: "lil_uzi_vert_vs_the_world",
  title: "Lil Uzi Vert vs. The World",
  artist: "Lil Uzi Vert",
  year: "2016",
  type: "official",
  tags: ["lil uzi vert","rap","2016"],
  cover: "https://upload.wikimedia.org/wikipedia/en/d/d5/LilUziVertVsTheWorld.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/lil-uzi-vert/lil-uzi-vert-vs-the-world/",
  tracks: [
    {name:"Canadian Goose",file:"canadian_goose.mp3",statId:"#LUVTW_CANADA"},
    {name:"Hi Roller",file:"hi_roller.mp3",statId:"#LUVTW_HIROLLER"},
    {name:"Money Longer",file:"money_longer.mp3",statId:"#LUVTW_ML"},
    {name:"Ps & Qs",file:"ps_and_qs.mp3",statId:"#LUVTW_PSQS"},
    {name:"You Was Right",file:"you_was_right.mp3",statId:"#LUVTW_YWR"},
    {name:"Baby Are You Home",file:"baby_are_you_home.mp3",statId:"#LUVTW_BAYH"},
    {name:"Scott and Ramona",file:"scott_and_ramona.mp3",statId:"#LUVTW_SAR"},
    {name:"The Way Life Goes",file:"the_way_life_goes.mp3",statId:"#LUVTW_TWLG"},
    {name:"For Real",file:"for_real.mp3",statId:"#LUVTW_FORREAL"}
  ]
},
{
  id: "eternal-atake",
  title: "Eternal Atake",
  artist: "Lil Uzi Vert",
  year: "2020",
  type: "official",
  tags: ["lil uzi vert","rap","2020"],
  cover: "https://i.ebayimg.com/images/g/9ToAAOSwJB5ksb0W/s-l1200.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/lil-uzi-vert/eternal-atake/",
  tracks: [
    {name:"Baby Pluto",file:"baby_pluto.mp3",statId:"#EA_BABY_PLUTO"},
    {name:"Lo Mein",file:"lo_mein.mp3",statId:"#EA_LO_MEIN"},
    {name:"Silly Watch",file:"silly_watch.mp3",statId:"#EA_SILLY_WATCH"},
    {name:"POP",file:"pop.mp3",statId:"#EA_POP"},
    {name:"You Better Move",file:"you_better_move.mp3",statId:"#EA_YBM"},
    {name:"Homecoming",file:"homecoming.mp3",statId:"#EA_HOMECOMING"},
    {name:"I Can Show You",file:"i_can_show_you.mp3",statId:"#EA_ICSY"},
    {name:"Venetia",file:"venetia.mp3",statId:"#EA_VENETIA"},
    {name:"Secure the Bag",file:"secure_the_bag.mp3",statId:"#EA_STB"},
    {name:"Prices",file:"prices.mp3",statId:"#EA_PRICES"},
    {name:"Urgency (feat. Syd)",file:"urgency.mp3",statId:"#EA_URGENCY"},
    {name:"Celebration Station",file:"celebration_station.mp3",statId:"#EA_CSTATION"},
    {name:"Bigger Than Life",file:"bigger_than_life.mp3",statId:"#EA_BTL"},
    {name:"Chrome Heart Tags",file:"chrome_heart_tags.mp3",statId:"#EA_CHT"},
    {name:"Bust Me",file:"bust_me.mp3",statId:"#EA_BUST_ME"},
    {name:"That Way",file:"that_way.mp3",statId:"#EA_THAT_WAY"},
    {name:"P2",file:"p2.mp3",statId:"#EA_P2"}
  ]
},
{
  id: "luv_vs_the_world_2",
  title: "Luv vs. The World 2",
  artist: "Lil Uzi Vert",
  year: "2020",
  type: "official",
  tags: ["lil uzi vert","rap","2020"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/Lil_Uzi_Vert_vs_the_World_2_cover_art.jpg/250px-Lil_Uzi_Vert_vs_the_World_2_cover_art.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/lil-uzi-vert/luv-vs-the-world-2/",
  tracks: [
    {name:"Myron",file:"myron.mp3",statId:"#LVTW2_MYRON"},
    {name:"Lotus",file:"lotus.mp3",statId:"#LVTW2_LOTUS"},
    {name:"Bean (Kobe)",file:"bean_kobe.mp3",statId:"#LVTW2_BEAN"},
    {name:"Yessirskiii (feat. 21 Savage)",file:"yessirskiii.mp3",statId:"#LVTW2_YESSIR"},
    {name:"Wassup",file:"wassup.mp3",statId:"#LVTW2_WASSUP"},
    {name:"Strawberry Peels (feat. Young Thug & Gunna)",file:"strawberry_peels.mp3",statId:"#LVTW2_SP"},
    {name:"Moon Relate",file:"moon_relate.mp3",statId:"#LVTW2_MOON"},
    {name:"Come This Way",file:"come_this_way.mp3",statId:"#LVTW2_CTW"},
    {name:"Trap This Way (This Way)",file:"trap_this_way.mp3",statId:"#LVTW2_TTW"},
    {name:"Got the Guap (feat. Young Thug)",file:"got_the_guap.mp3",statId:"#LVTW2_GTG"},
    {name:"Leaders (feat. NAV)",file:"leaders.mp3",statId:"#LVTW2_LEADERS"},
    {name:"Baby Pluto",file:"baby_pluto.mp3",statId:"#LVTW2_BABY_PLUTO"},
    {name:"P2",file:"p2.mp3",statId:"#LVTW2_P2"}
  ]
},
{
  id: "pink-tape",
  title: "Pink Tape",
  artist: "Lil Uzi Vert",
  year: "2023",
  type: "official",
  tags: ["lil uzi vert","rap","2023"],
  cover: "https://m.media-amazon.com/images/I/91mf0aFkILL._UF1000,1000_QL80_.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/lil-uzi-vert/pink-tape/",
  tracks: [
    {name:"Flooded the Face",file:"flooded_the_face.mp3",statId:"#PT_FLOODED"},
    {name:"Suicide Doors",file:"suicide_doors.mp3",statId:"#PT_SUICIDE"},
    {name:"Aye",file:"aye.mp3",statId:"#PT_AYE"},
    {name:"Crush Em",file:"crush_em.mp3",statId:"#PT_CRUSH"},
    {name:"Amped",file:"amped.mp3",statId:"#PT_AMPED"},
    {name:"x2",file:"x2.mp3",statId:"#PT_X2"},
    {name:"Died and Came Back",file:"died_and_came_back.mp3",statId:"#PT_DIED"},
    {name:"Spin Again",file:"spin_again.mp3",statId:"#PT_SPIN"},
    {name:"That Fiya",file:"that_fiya.mp3",statId:"#PT_FIYA"},
    {name:"I Gotta",file:"i_gotta.mp3",statId:"#PT_IGOTTA"},
    {name:"Endless Fashion (feat. Nicki Minaj)",file:"endless_fashion.mp3",statId:"#PT_ENDLESS"},
    {name:"Mama, I'm Sorry",file:"mama_im_sorry.mp3",statId:"#PT_MAMA"},
    {name:"All Alone",file:"all_alone.mp3",statId:"#PT_ALONE"},
    {name:"Nakamura",file:"nakamura.mp3",statId:"#PT_NAKAMURA"},
    {name:"Just Wanna Rock",file:"just_wanna_rock.mp3",statId:"#PT_JWR"},
    {name:"Patience",file:"patience.mp3",statId:"#PT_PATIENCE"},
    {name:"CS",file:"cs.mp3",statId:"#PT_CS"},
    {name:"Werewolf",file:"werewolf.mp3",statId:"#PT_WEREWOLF"},
    {name:"Pluto to Mars",file:"pluto_to_mars.mp3",statId:"#PT_PLUTO"},
    {name:"Days Come and Go",file:"days_come_and_go.mp3",statId:"#PT_DAYS"},
    {name:"Rehab",file:"rehab.mp3",statId:"#PT_REHAB"},
    {name:"The End (feat. BABYMETAL)",file:"the_end.mp3",statId:"#PT_THE_END"}
  ]
},

// ─── TRAVIS SCOTT (no tracks — display only) ──────────
{
  id: "astroworld",
  title: "AstroWorld.",
  artist: "Travis Scott",
  year: "2018",
  type: "released",
  tags: ["astroworld","travis scott","astro","world"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4b/Travis_Scott_-_Astroworld.png/250px-Travis_Scott_-_Astroworld.png",
  baseUrl: "",
  tracks: []
},
{
  id: "rodeo",
  title: "Rodeo",
  artist: "Travis Scott",
  year: "2015",
  type: "released",
  tags: ["rodeo","travis scott","2015"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/1/15/Travis_Scott_-_Rodeo.png/250px-Travis_Scott_-_Rodeo.png",
  baseUrl: "",
  tracks: []
},
{
  id: "days-before-rodeo",
  title: "Days Before Rodeo",
  artist: "Travis Scott",
  year: "2014",
  type: "released",
  tags: ["days","rodeo","travis scott","2014"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/5/58/Days_Before_Rodeo_Cover_Art.jpg/250px-Days_Before_Rodeo_Cover_Art.jpg",
  baseUrl: "",
  tracks: []
},
{
  id: "bittsmk",
  title: "Birds in the Trap Sing McKnight",
  artist: "Travis Scott",
  year: "2016",
  type: "released",
  tags: ["birds in the trap","McKnight","travis scott","2016"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/6/61/Travis_Scott_-_Birds_in_the_Trap_Sing_McKnight.png/250px-Travis_Scott_-_Birds_in_the_Trap_Sing_McKnight.png",
  baseUrl: "",
  tracks: []
},
{
  id: "jack-boys",
  title: "Jack Boys",
  artist: "Travis Scott",
  year: "2019",
  type: "released",
  tags: ["Jack boys","travis scott","sofaygo","chase b","2019"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/8/82/JACKBOYS_-_Album_Cover_by_JACKBOYS_%26_Travis_Scott%2C_December_27%2C_2019.jpg/250px-JACKBOYS_-_Album_Cover_by_JACKBOYS_%26_Travis_Scott%2C_December_27%2C_2019.jpg",
  baseUrl: "",
  tracks: []
},
{
  id: "jack-boys-2",
  title: "Jack Boys 2",
  artist: "Travis Scott",
  year: "2025",
  type: "released",
  tags: ["Jack boys","travis scott","sofaygo","chase b","don toliver","2025"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/7/75/JACKBOYS_2_-_Album_Cover_by_JACKBOYS_%26_Travis_Scott.png/250px-JACKBOYS_2_-_Album_Cover_by_JACKBOYS_%26_Travis_Scott.png",
  baseUrl: "",
  tracks: []
},

// ─── UNRELEASED ───────────────────────────────────────
{
  id: "yandhi",
  title: "Yandhi",
  artist: "Kanye West",
  year: "2018 (unreleased)",
  type: "unreleased",
  tags: ["kanye","west","yandhi","unreleased","shelved","rap","2018"],
  cover: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Yandhi_Cover_Art_%28Free_License%29.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kanye-west/yandhi/",
  tracks: [
    {name:"Chakras",file:"chakras.mp3",statId:"$YAN_CHAK"},
    {name:"Garden",file:"garden.mp3",statId:"$YAN_GARD"},
    {name:"New Body",file:"new-body.mp3",statId:"$YAN_NB"},
    {name:"Vibez",file:"vibez.mp3",statId:"$YAN_VIB"},
    {name:"Easy",file:"easy.mp3",statId:"$YAN_EASY"},
    {name:"Brothers",file:"brothers.mp3",statId:"$YAN_BRO"},
    {name:"Like God",file:"like-god.mp3",statId:"$YAN_LG"},
    {name:"Yandhi",file:"yandhi-title.mp3",statId:"$YAN_YAN"},
    {name:"Violent Crimes",file:"violent-crimes.mp3",statId:"$YAN_VC"},
    {name:"Nah Nah Nah",file:"nah-nah-nah.mp3",statId:"$YAN_NNN"},
    {name:"Background Noise",file:"background-noise.mp3",statId:"$YAN_BN"},
    {name:"True Love",file:"true-love-yandhi.mp3",statId:"$YAN_TL"},
    {name:"In the Fire",file:"in-the-fire.mp3",statId:"$YAN_ITF"}
  ]
},
{
  id: "turbo-grafx-16",
  title: "Turbo Grafx 16",
  artist: "Kanye West",
  year: "2019 (unreleased)",
  type: "unreleased",
  tags: ["kanye","west","turbo","grafx","16","unreleased","shelved","rap","2019"],
  cover: "https://lastfm.freetls.fastly.net/i/u/ar0/68bd0237ddfa94159b35a684e5ee8be7.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/kanye-west/turbo-grafx-16/",
  tracks: [
    {name:"Nah Nah Nah (OG)",file:"nah-nah-nah-og.mp3",statId:"$TG_NNN"},
    {name:"Turbo Grafx 16",file:"turbo-title.mp3",statId:"$TG_TG"},
    {name:"Water (Coachella)",file:"water-coachella.mp3",statId:"$TG_WAT"},
    {name:"Closed on Sunday (Early)",file:"closed-early.mp3",statId:"$TG_COS"},
    {name:"Follow God (Rough)",file:"follow-god-rough.mp3",statId:"$TG_FG"},
    {name:"God's Country",file:"gods-country.mp3",statId:"$TG_GC"},
    {name:"Everything We Need (Demo)",file:"ewen-demo.mp3",statId:"$TG_EWN"},
    {name:"Hands On (Early)",file:"hands-on-early.mp3",statId:"$TG_HO"},
    {name:"Use This Gospel (Demo)",file:"utg-demo.mp3",statId:"$TG_UTG"},
    {name:"Jesus Is Lord (Rough)",file:"jil-rough.mp3",statId:"$TG_JIL"}
  ]
},
{
  id: "eternal-atake-og",
  title: "Eternal Atake (OG Leak)",
  artist: "Lil Uzi Vert",
  year: "leaked 2019",
  type: "unreleased",
  tags: ["liluzivert","ea","2019"],
  cover: "https://i.redd.it/uby2xk33ybd11.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/lil-uzi-vert/eternal-atake-og/tracks/",
  tracks: [
    {name:"Lets Go",file:"lets-go.mp3",statId:"$EA_LETSGO"},
    {name:"Bands",file:"bands.m4a",statId:"$EA_BANDS"},
    {name:"You A 10",file:"you-a-ten-lotus-og.m4a",statId:"$EA_YOUA10"},
    {name:"Put That Money Up",file:"put-that-money-up.m4a",statId:"$EA_PUTTHATMONEYUP"},
    {name:"Blue Tips",file:"blue-tips-relationships.m4a",statId:"$EA_BLUETIPS"},
    {name:"Sticky",file:"sticky.m4a",statId:"$EA_STICKY"},
    {name:"Take My Cake",file:"take-my-cake.m4a",statId:"$EA_TAKEMYCAKE"},
    {name:"All My Guap",file:"all-my-guap.m4a",statId:"$EA_ALLMYGUAP"},
    {name:"Keep It Real",file:"keep-it-real.m4a",statId:"$EA_KEEPITREAL"},
    {name:"Diamonds",file:"diamonds.mp3",statId:"$EA_DIAMONDS"},
    {name:"Of Course",file:"ofc.m4a",statId:"$EA_OFCOURSE"},
    {name:"1600 (RAGER ANTHEM)",file:"rager-anthem-1600.m4a",statId:"$EA_1600RAGERANTHEM"},
    {name:"Not The Same",file:"not-the-same.m4a",statId:"$EA_NOTTHESAME"},
    {name:"Closure",file:"closure.m4a",statId:"$EA_CLOSURE"},
    {name:"Extraed Out",file:"extraed-out_keep-being-me.m4a",statId:"$EA_EXTRAEDOUT"},
    {name:"Run It Up",file:"run-it-up.m4a",statId:"$EA_RUNITUP"},
    {name:"Extra - New Patek",file:"bonus_new-patek.m4a",statId:"$EA_EXTRANEWPATEK"},
    {name:"Extra - The End Is Near",file:"bonus_the-end-is-near.m4a",statId:"$EA_EXTRATHEENDISNEAR"}
  ]
},
{
  id: "16-29-collab",
  title: "16*29",
  artist: "Lil Uzi Vert & Playboi Carti",
  year: "unreleased",
  type: "unreleased",
  tags: ["liluzivert","playboicarti","collab","1629"],
  cover: "https://i.pinimg.com/736x/59/4c/1c/594c1c54684244b2feda1fc9650e4f14.jpg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/lil-uzi-vert/16-29-collab/",
  tracks: [
    {name:"Intro (16*29)",file:"intro1629.mp3",statId:"$1629_INTRO"},
    {name:"Fell In Luv",file:"fellinluv.mp3",statId:"$1629_FELLINLUV"},
    {name:"No Stylist",file:"nostylist.mp3",statId:"$1629_NOSTYLIST"},
    {name:"Drip Season",file:"dripseason.mp3",statId:"$1629_DRIPSEASON"},
    {name:"Twin Turbos",file:"twinturbos.mp3",statId:"$1629_TWINTURBOS"},
    {name:"Slatt Walk",file:"slattwalk.mp3",statId:"$1629_SLATTWALK"},
    {name:"On Site (feat. Lil Uzi Vert)",file:"onsite.mp3",statId:"$1629_ONSITE"},
    {name:"Rockstar Shit",file:"rockstarshit.mp3",statId:"$1629_ROCKSTARSHIT"},
    {name:"Purple Haze",file:"purplehaze.mp3",statId:"$1629_PURPLEHAZE"},
    {name:"Rager 4 Life",file:"rager4life.mp3",statId:"$1629_RAGER4LIFE"},
    {name:"No Ceilings",file:"noceilings.mp3",statId:"$1629_NOCEILINGS"},
    {name:"Eternal Rage",file:"eternalrage.mp3",statId:"$1629_ETERNALRAGE"},
    {name:"Iced Out Halo",file:"icedouthalo.mp3",statId:"$1629_ICEDOUTHALO"},
    {name:"Carti Season",file:"cartiseason.mp3",statId:"$1629_CARTISEASON"},
    {name:"Outro (End Of Days)",file:"outroendofdays.mp3",statId:"$1629_OUTRO"}
  ]
},
{
  id: "bastard",
  title: "Bastard",
  artist: "Tyler, the Creator",
  year: "2009",
  type: "unreleased",
  tags: ["tyler the creator","rap","2009","mixtape"],
  cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/bastard/covers/IMG_6376.png",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/tyler-the-creator/bastard/",
  tracks: [
    {name:"Bastard",file:"bastard.mp3",statId:"$BAS_BAS"},
    {name:"Seven",file:"seven.mp3",statId:"$BAS_SEV"},
    {name:"Odd Toddlers (feat. Casey Veggies)",file:"odd-toddlers.mp3",statId:"$BAS_OT"},
    {name:"French!",file:"french.mp3",statId:"$BAS_FR"},
    {name:"Blow",file:"blow.mp3",statId:"$BAS_BL"},
    {name:"Pigs Fly (feat. Domo Genesis)",file:"pigs-fly.mp3",statId:"$BAS_PF"},
    {name:"Parade",file:"parade.mp3",statId:"$BAS_PAR"},
    {name:"Slow It Down (feat. Hodgy)",file:"slow-it-down.mp3",statId:"$BAS_SID"},
    {name:"AssMilk (feat. Earl Sweatshirt)",file:"assmilk.mp3",statId:"$BAS_AM"},
    {name:"VCR/Wheels",file:"vcr-wheels.mp3",statId:"$BAS_VW"},
    {name:"Session (feat. Hodgy & Mike G)",file:"session.mp3",statId:"$BAS_SES"},
    {name:"Sarah",file:"sarah.mp3",statId:"$BAS_SAR"},
    {name:"Jack and the Beanstalk",file:"jack-and-the-beanstalk.mp3",statId:"$BAS_JB"},
    {name:"Tina (feat. Jasper & Taco)",file:"tina.mp3",statId:"$BAS_TIN"},
    {name:"Inglorious",file:"inglorious.mp3",statId:"$BAS_ING"}
  ]
},

// ─── RHAP5ODY ─────────────────────────────────────────
{
  id: "maybe-maybe",
  title: "maybe (Maybe).",
  artist: "Rhap5ody",
  year: "2029 (soon)",
  type: "unreleased",
  tags: ["rhap5dy","maybe","2029"],
  cover: "https://raw.githubusercontent.com/bguhm/bguhm.github.io/main/music/albums/maybe-maybe/maybe-maybe-cover-art.png",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/rhap5ody/maybe-maybe/",
  tracks: [
    {name:"slackrr.",file:"slackrr.mp3",statId:"$MM_SLK"},
    {name:"Caramel eyes.",file:"caramel-eyes.mp3",statId:"$MM_CE"},
    {name:"PUNK HAZARD.",file:"punk-hazard.mp3",statId:"$MM_PH"},
    {name:"HOUND.",file:"hound.mp3",statId:"$MM_HND"},
    {name:"Arizona Girl",file:"arizona-girl.mp3",statId:"$MM_AZ"},
    {name:"MARIGOLD.",file:"marigold.mp3",statId:"$MM_MG"},
    {name:"Besto Friendo",file:"besto-friendo.mp3",statId:"$MM_BF"},
    {name:"HippoCript.",file:"hippocript.mp3",statId:"$MM_HC"},
    {name:"AloneAgain",file:"alone-again.mp3",statId:"$MM_AA"},
    {name:"RoofTop",file:"rooftop.mp3",statId:"$MM_RT"},
    {name:"November.",file:"november.mp3",statId:"$MM_NOV"},
    {name:"Street",file:"street.mp3",statId:"$MM_STR"},
    {name:"Self Conscious.",file:"self-conscious.mp3",statId:"$MM_SC"},
    {name:"Scribble.",file:"scribble.mp3",statId:"$MM_SCR"},
    {name:"Feelings In A Bottle.",file:"feelings-in-a-bottle.mp3",statId:"$MM_FIAB"},
    {name:"SoloCup.",file:"solocup.mp3",statId:"$MM_SOL"},
    {name:"Bg.uhm",file:"bg-uhm.mp3",statId:"$MM_BG"},
    {name:"6:27",file:"6-27.mp3",statId:"$MM_627"},
    {name:"Daisy.",file:"daisy.mp3",statId:"$MM_DAISY"},
    {name:"Maybe (Maybe).",file:"maybe-maybe.m4a",statId:"$MM_MM"}
  ]
},
{
  id: "syndicate",
  title: "Syndicate",
  artist: "Rhap5ody",
  year: "2029 (soon)",
  type: "unreleased",
  tags: ["syndicate","rhap5ody","2029"],
  cover: "https://raw.githubusercontent.com/bguhm/bguhm.github.io/main/music/albums/syndicate/Untitled157_20260219144858.png",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/rhap5ody/syndicate/",
  tracks: [
    {name:"BOHEMETH.",file:"bohemeth.mp3",statId:"$SYN_BOH"}
  ]
},
{
  id: "nuralistics",
  title: "NURALISTICS",
  artist: "Rhap5ody",
  year: "2029 (soon)",
  type: "unreleased",
  tags: ["NURALISTICS","rhap5ody","insomnia","2029"],
  cover: "https://raw.githubusercontent.com/bguhm/bguhm.github.io/main/music/albums/NURALISTICS/IMG_6099.png",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/rhap5ody/nuralistics/",
  tracks: [
    {name:"1",file:"#"},{name:"2",file:"#"},{name:"3",file:"#"},
    {name:"4",file:"#"},{name:"5",file:"#"},{name:"6",file:"#"},
    {name:"7",file:"#"},{name:"8",file:"#"},{name:"9",file:"#"},
    {name:"10",file:"#"},{name:"11",file:"#"},{name:"12",file:"#"},
    {name:"13.",file:"insomnia.mp3",statId:"$NUR_INS"}
  ]
},
{
  id: "r5",
  title: "rhapsody",
  artist: "Rhap5ody",
  year: "2029 (soon)",
  type: "unreleased",
  tags: ["rhap5ody","r5","2029"],
  cover: "https://raw.githubusercontent.com/bguhm/bguhm.github.io/main/music/albums/r5/IMG_6100.png",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/rhap5ody/r5/",
  tracks: [
    {name:"R5 DO THAT SHIT.",file:"r5dothatshit.mp3",statId:"$R5_R5DOTHATSHIT"},
    {name:"Tital",file:"#"},{name:"psych.",file:"#"},
    {name:"too high",file:"#"},{name:"IQ",file:"#"},{name:"MyWorld.",file:"#"}
  ]
},
{
  id: "phosephenes",
  title: "Phosphenes.",
  artist: "Rhap5ody",
  year: "2029",
  type: "unreleased",
  tags: ["Phonesphenes","phonesphenes","helloworld","HelloWorld","BeauTeen","beauteen","Moron Child","moron child"],
  cover: "https://raw.githubusercontent.com/dontevenjokelad/dontevenjokelad.github.io/main/audio/phosphenes/covers/Phosphenes.png",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/rhap5ody/phosphenes/",
  tracks: [
    {name:"HelloWorld!",file:"hello-world.mp3",statId:"$PS_HW"},
    {name:"Colorful World.",file:"colorful-world.mp3",statId:"$PS_CW"},
    {name:"Blood Flowers",file:"blood-flowers.mp3",statId:"$PS_BF"},
    {name:"Bloom.",file:"bloom.mp3",statId:"$PS_BM"},
    {name:"Slackerish.",file:"slackerish.mp3",statId:"$PS_ISH"},
    {name:"YartK",file:"yartk.mp3",statId:"$PS_YK"},
    {name:"Moron Child.",file:"moron-child.mp3",statId:"$PS_MC"},
    {name:"PerfectWorld.",file:"perfect-world.mp3",statId:"$PS_PW"}
  ]
},
{
  id: "no-luv-lost",
  title: "No Luv Lost",
  artist: "Lil Uzi Vert",
  year: "leaked?",
  type: "unreleased",
  tags: [],
  cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/no-luv-lost/covers/IMG_6389.jpeg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/lil-uzi-vert/no-luv-lost/",
  tracks: [
    {name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"}
  ]
},
{
  id: "wlr-v1",
  title: "whole lotta red v1",
  artist: "Playboi Carti",
  year: "leaked?",
  type: "unreleased",
  tags: [],
  cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/whole-lotta-red-v1/covers/IMG_6392.jpeg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/playboi-carti/wlr-v1/",
  tracks: [
    {name:"Not Real",file:"#"},{name:"Proud of You",file:"#"},{name:"Neon",file:"#"},
    {name:"Nine Nine",file:"#"},{name:"Vivienne Westwood",file:"#"},{name:"Designer Shoes",file:"#"},
    {name:"Bouldercrest (ft. Offset)",file:"#"},{name:"Moshpit (ft. NGeeYL)",file:"#"},
    {name:"Fashion Killa",file:"#"},{name:"Shopping Spree",file:"#"},
    {name:"I Promise You !",file:"#"},{name:"Back Up (ft. Offset)",file:"#"},
    {name:"Pop Bottles",file:"#"},{name:"Fuck it Up",file:"#"},
    {name:"Buffy the Body",file:"#"},{name:"RiRi",file:"#"}
  ]
},
{
  id: "the-world-pt1",
  title: "TheWorld pt.1",
  artist: "Rhap5ody",
  year: "2029",
  type: "unreleased",
  tags: [],
  cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/theworldpt1/covers/IMG_6393.jpeg",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/rhap5ody/the-world-pt1/",
  tracks: [
    {name:"90 degrees in the summer",file:"#"},{name:"Untitled",file:"#"},
    {name:"Untitled",file:"#"},{name:"Untitled",file:"#"},
    {name:"Friday",file:"#"},{name:"Life",file:"#"},
    {name:"influence",file:"#"},{name:"reverse",file:"#"}
  ]
},
{
  id: "theworldpt2",
  title: "TheWorld pt.2",
  artist: "Rhap5ody",
  year: "2029",
  type: "unreleased",
  tags: [],
  cover: "",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/rhap5ody/the-world-pt2/",
  tracks: [
    {name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"},
    {name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"}
  ]
},
{
  id: "theworldpt3",
  title: "TheWorld pt.3",
  artist: "Rhap5ody",
  year: "2029",
  type: "unreleased",
  tags: [],
  cover: "",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/rhap5ody/the-world-pt3/",
  tracks: [
    {name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"},
    {name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"}
  ]
},
{
  id: "theworldpt4",
  title: "TheWorld pt.4",
  artist: "Rhap5ody",
  year: "2029",
  type: "unreleased",
  tags: [],
  cover: "",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/rhap5ody/the-world-pt4/",
  tracks: [
    {name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"},
    {name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"}
  ]
},
{
  id: "slackrr",
  title: "slackrr",
  artist: "Rhap5ody",
  year: "2029",
  type: "unreleased",
  tags: ["rhapsody","2029"],
  cover: "",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/rhap5ody/slackrr/",
  tracks: [
    {name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"},
    {name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"}
  ]
},
{
  id: "jayda",
  title: "Jayda.",
  artist: "Rhap5ody",
  year: "2029",
  type: "unreleased",
  tags: [],
  cover: "",
  baseUrl: "https://cdn.jsdelivr.net/gh/dontevenjokelad/dontevenjokelad.github.io@main/audio/rhap5ody/jayda/",
  tracks: [
    {name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"},
    {name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"},{name:"title",file:"#"}
  ]
}

];